<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-AmbroBlogProject-F73243E5-2D5C-46DF-AC0C-AD14CE8B0505</UserSecretsId>
    <CopyRefAssembliesToPublishDirectory>false</CopyRefAssembliesToPublishDirectory>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.3" />
    <PackageReference Include="MimeKit" Version="4.17.0" />
    <PackageReference Include="Npgsql" Version="10.0.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
    <PackageReference Include="X.PagedList" Version="10.5.9" />
    <PackageReference Include="X.PagedList.EF" Version="10.5.9" />
    <PackageReference Include="X.PagedList.Mvc.Core" Version="10.5.9" />
    <PackageReference Include="X.PagedList.Web.Common" Version="8.0.7" />
  </ItemGroup>

</Project>
